### ISSUE TITLE
Genes no showing when loading a genome from json file

### ISSUE THREAD

**Issue by r78v10a07** [igvteam/igv-webapp#301] opened 2024-08-23 16:45 UTC
I attached a genome json file that fail to show the genes when clicking a chromosome.

[tair10.json](https://github.com/user-attachments/files/16731515/tair10.json)

After loading the genomes all chromosomes are shown correctly

<img width="1452" alt="Screenshot 2024-08-23 at 6 39 12 PM" src="https://github.com/user-attachments/assets/6df8a146-cc26-4bd8-a20b-114db1515e77">

Then, clicking on any chromosome (figure show chromosome 3) the genes are not shown

<img width="1452" alt="Screenshot 2024-08-23 at 6 39 48 PM" src="https://github.com/user-attachments/assets/ac171245-987a-4f2c-b80c-9d55a9cd3716">

Can you tell me if there is anything wrong with my json format or files?

**Comment by jrobinso** [comment] 2024-08-23 18:21
The json is fine.   The error is caused by the index, loading the file without the index works.   I'm investigating, it could be an igv.js bug, not the index itself.

**Comment by jrobinso** [comment] 2024-08-26 06:02
I found this issue,  it affects a small number of indexed GFF files, which unfortunately includes yours.   I will have a fix soon.

**Comment by jrobinso** [comment] 2024-08-26 22:19
This have been fixed in igv-webapp v 2.0.3.   The fix is actually in igv.js. (v 3.0.4)

**Closed by jrobinso** 2024-08-26 22:19 UTC
